### ISSUE TITLE
CRDs resulting in 406 NotAcceptable

### ISSUE THREAD

**Issue by vlerenc** [smpio/kube-browser#26]
Great tool, thanks! When opening a CRD, I get 406 NotAcceptable (application/json).
> `406 NotAcceptable only the following media types are accepted: application/json`

**Comment by brokenmass** [comment]
it's a bug in kubernetes api, solved in kubernetes 1.10 https://github.com/kubernetes/kubernetes/pull/58260

**Comment by uqee** [comment]
@brokenmass Good to hear from you, thanks!
