### ISSUE TITLE
undefined undefined

### ISSUE THREAD

**Issue by TheYkk** [smpio/kube-browser#38]
![image](https://user-images.githubusercontent.com/21688838/59151526-511cf080-8a3d-11e9-9363-8e948b18cca8.png)
![image](https://user-images.githubusercontent.com/21688838/59151527-5843fe80-8a3d-11e9-8783-1ff1ff983749.png)
![image](https://user-images.githubusercontent.com/21688838/59151528-6265fd00-8a3d-11e9-8457-47601088edd9.png)
![image](https://user-images.githubusercontent.com/21688838/59151531-67c34780-8a3d-11e9-9102-e46a3df1c260.png)
![image](https://user-images.githubusercontent.com/21688838/59151534-6db92880-8a3d-11e9-8f3e-4490930bf197.png)

**Comment by PaulFurtado** [comment]
Looks like the issue here is that kubernetes got rid of the /swaggerapi endpoint. It seems to work otherwise so I wonder if the swagger code can just be removed
